image: mcr.microsoft.com/dotnet/sdk:9.0

stages: 
  - build

build:
  stage: build
  script:
    - dotnet build Website -v q --configuration Release
  artifacts:
    paths:
      - bin/Release/
    expire_in: 1 day
