image: mcr.microsoft.com/dotnet/sdk:9.0

stages:
  - restore
  - build

restore-dependencies:
  stage: restore
  before_script:
    - mkdir -p ~/.nuget/packages/
  script:
    - dotnet restore
  cache:
    key: nuget
    paths:
      - ~/.nuget/packages/
    policy: pull-push

build:
  stage: build
  script:
    - dotnet build --configuration Release --no-restore
  dependencies:
    - restore-dependencies
  artifacts:
    paths:
      - bin/Release/
    expire_in: 1 day
