image: mcr.microsoft.com/dotnet/sdk:9.0

stages: 
  - build_webapp
  - run_tests

build:
  stage: build_webapp
  script:
    - dotnet build Website -v q --configuration Release

run_tests:
  stage: run_tests
  script:
    - dotnet test