image: mcr.microsoft.com/dotnet/sdk:9.0

stages: 
  - build

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: 1
  DOTNET_NOLOGO: true

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .nuget/packages/

before_script:
  - echo "Using .NET $(dotnet --version)"
  - dotnet --info
 

build:
  stage: build
  script:
    - dotnet build --configuration Release
  artifacts:
    paths:
      - bin/
      - obj/
    expire_in: 1h
