
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.1.1.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace WebsiteSetupGui {
    using System;
    using Terminal.Gui;
    
    
    public partial class MainView : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label;
        
        private Terminal.Gui.FrameView frameView;
        
        private Terminal.Gui.Button setup;
        
        private Terminal.Gui.Button edit;
        
        private Terminal.Gui.Button reset;
        
        private Terminal.Gui.Button quit;
        
        private void InitializeComponent() {
            this.quit = new Terminal.Gui.Button();
            this.reset = new Terminal.Gui.Button();
            this.edit = new Terminal.Gui.Button();
            this.setup = new Terminal.Gui.Button();
            this.frameView = new Terminal.Gui.FrameView();
            this.label = new Terminal.Gui.Label();
            this.Width = Dim.Fill(0);
            this.Height = Dim.Fill(0);
            this.X = 0;
            this.Y = 0;
            this.Visible = true;
            this.Modal = false;
            this.IsMdiContainer = false;
            this.Border.BorderStyle = Terminal.Gui.BorderStyle.Single;
            this.Border.Effect3D = false;
            this.Border.Effect3DBrush = null;
            this.Border.DrawMarginFrame = true;
            this.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Title = "Press Ctrl+Q to quit";
            this.label.Width = 4;
            this.label.Height = 1;
            this.label.X = Pos.Center();
            this.label.Y = Pos.Percent(25f) - 3;
            this.label.Visible = true;
            this.label.Data = "label";
            this.label.Text = "BugTracker TUI";
            this.label.TextAlignment = Terminal.Gui.TextAlignment.Left;
            this.Add(this.label);
            this.frameView.Width = 30;
            this.frameView.Height = 7;
            this.frameView.X = Pos.Center();
            this.frameView.Y = Pos.Center();
            this.frameView.Visible = true;
            this.frameView.Data = "frameView";
            this.frameView.Border.BorderStyle = Terminal.Gui.BorderStyle.Double;
            this.frameView.Border.Effect3D = false;
            this.frameView.Border.Effect3DBrush = null;
            this.frameView.Border.DrawMarginFrame = true;
            this.frameView.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.frameView.Title = "Select option";
            this.Add(this.frameView);
            this.setup.Width = Dim.Fill(0);
            this.setup.Height = 1;
            this.setup.X = 0;
            this.setup.Y = 0;
            this.setup.Visible = true;
            this.setup.Data = "setup";
            this.setup.Text = "Setup";
            this.setup.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.setup.IsDefault = false;
            this.frameView.Add(this.setup);
            this.edit.Width = Dim.Fill(0);
            this.edit.Height = 1;
            this.edit.X = 0;
            this.edit.Y = 1;
            this.edit.Visible = true;
            this.edit.Data = "edit";
            this.edit.Text = "Edit";
            this.edit.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.edit.IsDefault = false;
            this.frameView.Add(this.edit);
            this.reset.Width = Dim.Fill(0);
            this.reset.Height = 1;
            this.reset.X = 0;
            this.reset.Y = 2;
            this.reset.Visible = true;
            this.reset.Data = "reset";
            this.reset.Text = "Reset";
            this.reset.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.reset.IsDefault = false;
            this.frameView.Add(this.reset);
            this.quit.Width = Dim.Fill(0);
            this.quit.Height = 1;
            this.quit.X = Pos.Center();
            this.quit.Y = 4;
            this.quit.Visible = true;
            this.quit.Data = "quit";
            this.quit.Text = "Quit";
            this.quit.TextAlignment = Terminal.Gui.TextAlignment.Justified;
            this.quit.IsDefault = false;
            this.frameView.Add(this.quit);
        }
    }
}
